const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto')
const dir=path.resolve(__dirname,'..'),built=process.argv.includes('--built'),base=built?'dist':'public'
const html=fs.readFileSync(path.join(dir,built?'dist/index.html':'index.html'),'utf8'),origin='https://play.motioncricket.workers.dev/'
const meta=(key,value)=>{const m=html.match(new RegExp(`<meta ${key}="${value}" content="([^"]+)"`));assert(m,`${value} metadata`);return m[1]}
assert(html.includes('<html lang="en">'));assert(meta('name','viewport').includes('width=device-width'))
assert.equal(html.match(/<title>([^<]+)<\/title>/)[1],'Motion Cricket – Motion-Controlled Cricket Game')
const description=meta('name','description');assert(description.length>=120&&description.length<=160);assert(description.includes('webcam hand tracking'));assert(description.includes('smartphone motion'))
assert.equal([...html.matchAll(/rel="canonical"/g)].length,1);assert(html.includes(`rel="canonical" href="${origin}"`))
assert(!/<meta[^>]+(?:name="(?:robots|googlebot)"[^>]+content="[^"]*noindex)/i.test(html))
assert.equal(meta('property','og:url'),origin);assert.equal(meta('property','og:site_name'),'Motion Cricket');assert.equal(meta('name','twitter:card'),'summary_large_image')
assert.equal(meta('property','og:description'),description);assert.equal(meta('name','twitter:description'),description)
const image=meta('property','og:image');assert.equal(meta('name','twitter:image'),image)
assert.equal(new URL(image).origin,new URL(origin).origin)
const imagePath=path.join(dir,base,new URL(image).pathname),source=path.resolve(dir,'../docs/assets/gameplay-hero.png')
const hash=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');assert.equal(hash(imagePath),hash(source),'Existing screenshot copied unchanged')
const schema=JSON.parse(html.match(/<script type="application\/ld\+json">([\s\S]*?)<\/script>/)[1]);assert.equal(schema['@type'],'WebApplication');assert.equal(schema.url,origin);assert.equal(schema.applicationCategory,'GameApplication')
for(const unsupported of ['offers','aggregateRating','review','publisher'])assert(!(unsupported in schema))
assert(html.includes('<h1>Motion Cricket</h1>'));assert(html.includes('physically move the bat with webcam hand tracking'));assert(html.includes('<noscript>'))
const robots=fs.readFileSync(path.join(dir,base,'robots.txt'),'utf8');assert(robots.includes('User-agent: *'));assert(robots.includes('Allow: /'));assert(!robots.includes('Disallow: /'));assert(robots.includes(`Sitemap: ${origin}sitemap.xml`))
const sitemap=fs.readFileSync(path.join(dir,base,'sitemap.xml'),'utf8');assert(sitemap.includes('http://www.sitemaps.org/schemas/sitemap/0.9'));assert.deepEqual([...sitemap.matchAll(/<loc>(.*?)<\/loc>/g)].map(m=>m[1]),[origin]);assert(!sitemap.includes('session='))
const headers=fs.readFileSync(path.join(dir,base,'_headers'),'utf8').replace(/\r\n/g,'\n');assert(headers.includes('/controller\n  X-Robots-Tag: noindex'));assert(!headers.match(/^\/\s*\n\s+X-Robots-Tag: noindex/m))
assert(!html.includes('motion-cricket.motion-cricket.workers.dev'));assert(!sitemap.includes('motion-cricket.motion-cricket.workers.dev'))
const menu=fs.readFileSync(path.join(dir,'src/MainMenu.tsx'),'utf8');assert(menu.includes('A browser cricket game.'));assert(menu.includes('Webcam hand tracking. Smartphone motion. Your physical swing.'))
console.log(`PASS: ${built?'built':'source'} title/description/canonical/social/schema, crawlable content, real OG asset, root-only sitemap/robots and controller noindex headers`)
